version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "17:45"
    timezone: Europe/Kiev
  open-pull-requests-limit: 10
  reviewers:
  - bullet-tooth
  ignore:
  - dependency-name: com.google.inject:guice
    versions:
    - "< 4.2.2, >= 4.2.1.a"
  - dependency-name: io.vertx:vertx-codegen
    versions:
    - ">= 3.6.2.a, < 3.6.3"
  - dependency-name: io.vertx:vertx-codegen
    versions:
    - ">= 3.6.3.a, < 3.6.4"
  - dependency-name: io.vertx:vertx-junit5
    versions:
    - ">= 3.6.2.a, < 3.6.3"
  - dependency-name: io.vertx:vertx-junit5
    versions:
    - ">= 3.6.3.a, < 3.6.4"
  - dependency-name: io.vertx:vertx-unit
    versions:
    - ">= 3.6.2.a, < 3.6.3"
  - dependency-name: io.vertx:vertx-unit
    versions:
    - ">= 3.6.3.a, < 3.6.4"
  - dependency-name: io.vertx:vertx-web
    versions:
    - ">= 3.6.2.a, < 3.6.3"
  - dependency-name: io.vertx:vertx-web
    versions:
    - ">= 3.6.3.a, < 3.6.4"
  - dependency-name: io.vertx:vertx-web-client
    versions:
    - ">= 3.6.2.a, < 3.6.3"
  - dependency-name: io.vertx:vertx-web-client
    versions:
    - ">= 3.6.3.a, < 3.6.4"
  - dependency-name: com.google.protobuf:protobuf-java
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: nl.jqno.equalsverifier:equalsverifier
    versions:
    - 3.5.2
    - 3.5.3
    - 3.5.4
    - 3.5.5
  - dependency-name: com.github.spotbugs:spotbugs-maven-plugin
    versions:
    - 4.2.0
    - 4.2.2
  - dependency-name: io.vertx:vertx-web
    versions:
    - 3.9.4
    - 4.0.0
  - dependency-name: io.vertx:vertx-junit5
    versions:
    - 3.9.4
    - 4.0.0
  - dependency-name: io.vertx:vertx-web-client
    versions:
    - 3.9.4
    - 4.0.0
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.5.13
    - 3.7.7
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.5.13
    - 3.7.7
  - dependency-name: com.google.auto.value:auto-value
    versions:
    - 1.7.4
  - dependency-name: com.google.auto.value:auto-value-annotations
    versions:
    - 1.7.4
  - dependency-name: com.goterl.lazycode:lazysodium-java
    versions:
    - 4.3.2
    - 4.3.3
  - dependency-name: com.squareup.okhttp3:mockwebserver
    versions:
    - 4.9.0
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
- package-ecosystem: cargo
  directory: "/exonum-java-binding/core/rust"
  schedule:
    interval: monthly
    time: "17:45"
    timezone: Europe/Kiev
  open-pull-requests-limit: 10
  reviewers:
  - aleksuss
  ignore:
  - dependency-name: exonum
    versions:
    - "< 0.9, > 0.8.1"
  - dependency-name: exonum-btc-anchoring
    versions:
    - "< 0.9, > 0.8.1"
  - dependency-name: exonum-configuration
    versions:
    - "< 0.9, > 0.8.0"
  - dependency-name: exonum-testkit
    versions:
    - "< 0.9, > 0.8.0"
  - dependency-name: futures
    versions:
    - "> 0.1.29"
  - dependency-name: serde
    versions:
    - 1.0.118
    - 1.0.123
  - dependency-name: tokio
    versions:
    - 1.0.1
    - 1.1.1
    - 1.2.0
  - dependency-name: anyhow
    versions:
    - 1.0.37
    - 1.0.38
  - dependency-name: log
    versions:
    - 0.4.11
- package-ecosystem: maven
  directory: "/exonum-java-binding/tutorials"
  schedule:
    interval: daily
    time: "17:45"
    timezone: Europe/Kiev
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.junit:junit-bom
    versions:
    - 5.7.0
