# An exonum-launcher configuration file for deploying and starting a service instance
# in the test network. Edit as needed.
#
# See:
#  - start-testnet.sh
#  - https://exonum.com/doc/version/latest/get-started/java-binding/#deploy-and-start-the-service
networks:
  - host: "127.0.0.1"
    ssl: false
    public-api-port: 3000
    private-api-port: 3010

deadline_height: 20000

runtimes:
  java: 1

plugins:
  runtime:
    java: "exonum_java_runtime_plugin.JavaDeploySpecLoader"

artifacts:
  ${rootArtifactId}:
    runtime: java
    name: "${groupId}/${rootArtifactId}-service"
    version: "${version}"
    spec:
      artifact_filename: "${rootArtifactId}-service-${version}-artifact.jar"
    action: deploy

instances:
  # A test service instance of "${rootArtifactId}-service".
  test-${artifactId}:
    artifact: ${artifactId}
    action: start
