[package]
name = "dy_tests"
version = "0.1.0"
authors = ["Exonum Team <exonum@bitfury.com>"]
publish = false
workspace = ".."

[features]
invocation = ["java_bindings/invocation", "jni/invocation"]

[dependencies]
java_bindings = { path = ".." }
jni = "0.9.0"
lazy_static = "1.0.0"
