// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessage.proto

package com.exonum.binding.common.serialization;

public final class TestProtos {
  private TestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 x = 1;</code>
     */
    int getX();

    /**
     * <code>sint32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code Point}
   */
  public  static final class Point extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Point)
      PointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point() {
      x_ = 0;
      y_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Point(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readSInt32();
              break;
            }
            case 16: {

              y_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exonum.binding.common.serialization.TestProtos.internal_static_Point_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exonum.binding.common.serialization.TestProtos.internal_static_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exonum.binding.common.serialization.TestProtos.Point.class, com.exonum.binding.common.serialization.TestProtos.Point.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>sint32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>sint32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeSInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeSInt32(2, y_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.exonum.binding.common.serialization.TestProtos.Point)) {
        return super.equals(obj);
      }
      com.exonum.binding.common.serialization.TestProtos.Point other = (com.exonum.binding.common.serialization.TestProtos.Point) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.exonum.binding.common.serialization.TestProtos.Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Point)
        com.exonum.binding.common.serialization.TestProtos.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.exonum.binding.common.serialization.TestProtos.internal_static_Point_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.exonum.binding.common.serialization.TestProtos.internal_static_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.exonum.binding.common.serialization.TestProtos.Point.class, com.exonum.binding.common.serialization.TestProtos.Point.Builder.class);
      }

      // Construct using com.exonum.binding.common.serialization.TestProtos.Point.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.exonum.binding.common.serialization.TestProtos.internal_static_Point_descriptor;
      }

      public com.exonum.binding.common.serialization.TestProtos.Point getDefaultInstanceForType() {
        return com.exonum.binding.common.serialization.TestProtos.Point.getDefaultInstance();
      }

      public com.exonum.binding.common.serialization.TestProtos.Point build() {
        com.exonum.binding.common.serialization.TestProtos.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.exonum.binding.common.serialization.TestProtos.Point buildPartial() {
        com.exonum.binding.common.serialization.TestProtos.Point result = new com.exonum.binding.common.serialization.TestProtos.Point(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.exonum.binding.common.serialization.TestProtos.Point) {
          return mergeFrom((com.exonum.binding.common.serialization.TestProtos.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.exonum.binding.common.serialization.TestProtos.Point other) {
        if (other == com.exonum.binding.common.serialization.TestProtos.Point.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.exonum.binding.common.serialization.TestProtos.Point parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.exonum.binding.common.serialization.TestProtos.Point) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>sint32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>sint32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>sint32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>sint32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Point)
    }

    // @@protoc_insertion_point(class_scope:Point)
    private static final com.exonum.binding.common.serialization.TestProtos.Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.exonum.binding.common.serialization.TestProtos.Point();
    }

    public static com.exonum.binding.common.serialization.TestProtos.Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Point(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    public com.exonum.binding.common.serialization.TestProtos.Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TargetsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Targets)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */
    int getTargetsCount();
    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */
    boolean containsTargets(
        java.lang.String key);
    /**
     * Use {@link #getTargetsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>
    getTargets();
    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */
    java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>
    getTargetsMap();
    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */

    com.exonum.binding.common.serialization.TestProtos.Point getTargetsOrDefault(
        java.lang.String key,
        com.exonum.binding.common.serialization.TestProtos.Point defaultValue);
    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */

    com.exonum.binding.common.serialization.TestProtos.Point getTargetsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code Targets}
   */
  public  static final class Targets extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Targets)
      TargetsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Targets.newBuilder() to construct.
    private Targets(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Targets() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Targets(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                targets_ = com.google.protobuf.MapField.newMapField(
                    TargetsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>
              targets__ = input.readMessage(
                  TargetsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              targets_.getMutableMap().put(
                  targets__.getKey(), targets__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exonum.binding.common.serialization.TestProtos.internal_static_Targets_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetTargets();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exonum.binding.common.serialization.TestProtos.internal_static_Targets_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exonum.binding.common.serialization.TestProtos.Targets.class, com.exonum.binding.common.serialization.TestProtos.Targets.Builder.class);
    }

    public static final int TARGETS_FIELD_NUMBER = 1;
    private static final class TargetsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>newDefaultInstance(
                  com.exonum.binding.common.serialization.TestProtos.internal_static_Targets_TargetsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.exonum.binding.common.serialization.TestProtos.Point.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> targets_;
    private com.google.protobuf.MapField<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>
    internalGetTargets() {
      if (targets_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TargetsDefaultEntryHolder.defaultEntry);
      }
      return targets_;
    }

    public int getTargetsCount() {
      return internalGetTargets().getMap().size();
    }
    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */

    public boolean containsTargets(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTargets().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTargetsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> getTargets() {
      return getTargetsMap();
    }
    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */

    public java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> getTargetsMap() {
      return internalGetTargets().getMap();
    }
    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */

    public com.exonum.binding.common.serialization.TestProtos.Point getTargetsOrDefault(
        java.lang.String key,
        com.exonum.binding.common.serialization.TestProtos.Point defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> map =
          internalGetTargets().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Target points by their names.
     * </pre>
     *
     * <code>map&lt;string, .Point&gt; targets = 1;</code>
     */

    public com.exonum.binding.common.serialization.TestProtos.Point getTargetsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> map =
          internalGetTargets().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTargets(),
          TargetsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> entry
           : internalGetTargets().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>
        targets__ = TargetsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, targets__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.exonum.binding.common.serialization.TestProtos.Targets)) {
        return super.equals(obj);
      }
      com.exonum.binding.common.serialization.TestProtos.Targets other = (com.exonum.binding.common.serialization.TestProtos.Targets) obj;

      boolean result = true;
      result = result && internalGetTargets().equals(
          other.internalGetTargets());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetTargets().getMap().isEmpty()) {
        hash = (37 * hash) + TARGETS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTargets().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.exonum.binding.common.serialization.TestProtos.Targets parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.exonum.binding.common.serialization.TestProtos.Targets prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Targets}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Targets)
        com.exonum.binding.common.serialization.TestProtos.TargetsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.exonum.binding.common.serialization.TestProtos.internal_static_Targets_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetTargets();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableTargets();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.exonum.binding.common.serialization.TestProtos.internal_static_Targets_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.exonum.binding.common.serialization.TestProtos.Targets.class, com.exonum.binding.common.serialization.TestProtos.Targets.Builder.class);
      }

      // Construct using com.exonum.binding.common.serialization.TestProtos.Targets.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableTargets().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.exonum.binding.common.serialization.TestProtos.internal_static_Targets_descriptor;
      }

      public com.exonum.binding.common.serialization.TestProtos.Targets getDefaultInstanceForType() {
        return com.exonum.binding.common.serialization.TestProtos.Targets.getDefaultInstance();
      }

      public com.exonum.binding.common.serialization.TestProtos.Targets build() {
        com.exonum.binding.common.serialization.TestProtos.Targets result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.exonum.binding.common.serialization.TestProtos.Targets buildPartial() {
        com.exonum.binding.common.serialization.TestProtos.Targets result = new com.exonum.binding.common.serialization.TestProtos.Targets(this);
        int from_bitField0_ = bitField0_;
        result.targets_ = internalGetTargets();
        result.targets_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.exonum.binding.common.serialization.TestProtos.Targets) {
          return mergeFrom((com.exonum.binding.common.serialization.TestProtos.Targets)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.exonum.binding.common.serialization.TestProtos.Targets other) {
        if (other == com.exonum.binding.common.serialization.TestProtos.Targets.getDefaultInstance()) return this;
        internalGetMutableTargets().mergeFrom(
            other.internalGetTargets());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.exonum.binding.common.serialization.TestProtos.Targets parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.exonum.binding.common.serialization.TestProtos.Targets) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> targets_;
      private com.google.protobuf.MapField<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>
      internalGetTargets() {
        if (targets_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TargetsDefaultEntryHolder.defaultEntry);
        }
        return targets_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>
      internalGetMutableTargets() {
        onChanged();;
        if (targets_ == null) {
          targets_ = com.google.protobuf.MapField.newMapField(
              TargetsDefaultEntryHolder.defaultEntry);
        }
        if (!targets_.isMutable()) {
          targets_ = targets_.copy();
        }
        return targets_;
      }

      public int getTargetsCount() {
        return internalGetTargets().getMap().size();
      }
      /**
       * <pre>
       * Target points by their names.
       * </pre>
       *
       * <code>map&lt;string, .Point&gt; targets = 1;</code>
       */

      public boolean containsTargets(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTargets().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTargetsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> getTargets() {
        return getTargetsMap();
      }
      /**
       * <pre>
       * Target points by their names.
       * </pre>
       *
       * <code>map&lt;string, .Point&gt; targets = 1;</code>
       */

      public java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> getTargetsMap() {
        return internalGetTargets().getMap();
      }
      /**
       * <pre>
       * Target points by their names.
       * </pre>
       *
       * <code>map&lt;string, .Point&gt; targets = 1;</code>
       */

      public com.exonum.binding.common.serialization.TestProtos.Point getTargetsOrDefault(
          java.lang.String key,
          com.exonum.binding.common.serialization.TestProtos.Point defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> map =
            internalGetTargets().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Target points by their names.
       * </pre>
       *
       * <code>map&lt;string, .Point&gt; targets = 1;</code>
       */

      public com.exonum.binding.common.serialization.TestProtos.Point getTargetsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> map =
            internalGetTargets().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTargets() {
        internalGetMutableTargets().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Target points by their names.
       * </pre>
       *
       * <code>map&lt;string, .Point&gt; targets = 1;</code>
       */

      public Builder removeTargets(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTargets().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point>
      getMutableTargets() {
        return internalGetMutableTargets().getMutableMap();
      }
      /**
       * <pre>
       * Target points by their names.
       * </pre>
       *
       * <code>map&lt;string, .Point&gt; targets = 1;</code>
       */
      public Builder putTargets(
          java.lang.String key,
          com.exonum.binding.common.serialization.TestProtos.Point value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTargets().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Target points by their names.
       * </pre>
       *
       * <code>map&lt;string, .Point&gt; targets = 1;</code>
       */

      public Builder putAllTargets(
          java.util.Map<java.lang.String, com.exonum.binding.common.serialization.TestProtos.Point> values) {
        internalGetMutableTargets().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Targets)
    }

    // @@protoc_insertion_point(class_scope:Targets)
    private static final com.exonum.binding.common.serialization.TestProtos.Targets DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.exonum.binding.common.serialization.TestProtos.Targets();
    }

    public static com.exonum.binding.common.serialization.TestProtos.Targets getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Targets>
        PARSER = new com.google.protobuf.AbstractParser<Targets>() {
      public Targets parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Targets(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Targets> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Targets> getParserForType() {
      return PARSER;
    }

    public com.exonum.binding.common.serialization.TestProtos.Targets getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Point_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Targets_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Targets_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Targets_TargetsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Targets_TargetsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021TestMessage.proto\"\035\n\005Point\022\t\n\001x\030\001 \001(\021\022" +
      "\t\n\001y\030\002 \001(\021\"i\n\007Targets\022&\n\007targets\030\001 \003(\0132\025" +
      ".Targets.TargetsEntry\0326\n\014TargetsEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\025\n\005value\030\002 \001(\0132\006.Point:\0028\001B5\n" +
      "\'com.exonum.binding.common.serialization" +
      "B\nTestProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Point_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_Targets_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Targets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Targets_descriptor,
        new java.lang.String[] { "Targets", });
    internal_static_Targets_TargetsEntry_descriptor =
      internal_static_Targets_descriptor.getNestedTypes().get(0);
    internal_static_Targets_TargetsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Targets_TargetsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
