# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_runtime.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_runtime.proto',
  package='exonum.java.runtime',
  syntax='proto3',
  serialized_options=_b('\n\037com.exonum.binding.core.runtimeB\024ServiceRuntimeProtos'),
  serialized_pb=_b('\n\x15service_runtime.proto\x12\x13\x65xonum.java.runtime\"\x80\x01\n\x19ServiceRuntimeStateHashes\x12\x1c\n\x14runtime_state_hashes\x18\x01 \x03(\x0c\x12\x45\n\x14service_state_hashes\x18\x02 \x03(\x0b\x32\'.exonum.java.runtime.ServiceStateHashes\"?\n\x12ServiceStateHashes\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x14\n\x0cstate_hashes\x18\x02 \x03(\x0c\",\n\x0f\x44\x65ployArguments\x12\x19\n\x11\x61rtifact_filename\x18\x01 \x01(\tB7\n\x1f\x63om.exonum.binding.core.runtimeB\x14ServiceRuntimeProtosb\x06proto3')
)




_SERVICERUNTIMESTATEHASHES = _descriptor.Descriptor(
  name='ServiceRuntimeStateHashes',
  full_name='exonum.java.runtime.ServiceRuntimeStateHashes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='runtime_state_hashes', full_name='exonum.java.runtime.ServiceRuntimeStateHashes.runtime_state_hashes', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_state_hashes', full_name='exonum.java.runtime.ServiceRuntimeStateHashes.service_state_hashes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=175,
)


_SERVICESTATEHASHES = _descriptor.Descriptor(
  name='ServiceStateHashes',
  full_name='exonum.java.runtime.ServiceStateHashes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='exonum.java.runtime.ServiceStateHashes.instance_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_hashes', full_name='exonum.java.runtime.ServiceStateHashes.state_hashes', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=240,
)


_DEPLOYARGUMENTS = _descriptor.Descriptor(
  name='DeployArguments',
  full_name='exonum.java.runtime.DeployArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='artifact_filename', full_name='exonum.java.runtime.DeployArguments.artifact_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=286,
)

_SERVICERUNTIMESTATEHASHES.fields_by_name['service_state_hashes'].message_type = _SERVICESTATEHASHES
DESCRIPTOR.message_types_by_name['ServiceRuntimeStateHashes'] = _SERVICERUNTIMESTATEHASHES
DESCRIPTOR.message_types_by_name['ServiceStateHashes'] = _SERVICESTATEHASHES
DESCRIPTOR.message_types_by_name['DeployArguments'] = _DEPLOYARGUMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceRuntimeStateHashes = _reflection.GeneratedProtocolMessageType('ServiceRuntimeStateHashes', (_message.Message,), dict(
  DESCRIPTOR = _SERVICERUNTIMESTATEHASHES,
  __module__ = 'service_runtime_pb2'
  # @@protoc_insertion_point(class_scope:exonum.java.runtime.ServiceRuntimeStateHashes)
  ))
_sym_db.RegisterMessage(ServiceRuntimeStateHashes)

ServiceStateHashes = _reflection.GeneratedProtocolMessageType('ServiceStateHashes', (_message.Message,), dict(
  DESCRIPTOR = _SERVICESTATEHASHES,
  __module__ = 'service_runtime_pb2'
  # @@protoc_insertion_point(class_scope:exonum.java.runtime.ServiceStateHashes)
  ))
_sym_db.RegisterMessage(ServiceStateHashes)

DeployArguments = _reflection.GeneratedProtocolMessageType('DeployArguments', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYARGUMENTS,
  __module__ = 'service_runtime_pb2'
  # @@protoc_insertion_point(class_scope:exonum.java.runtime.DeployArguments)
  ))
_sym_db.RegisterMessage(DeployArguments)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
