consensus_public_key = "cbc9ffef062abe970087273f14bfdadbc5d5c5b51cb2fb8a386d960d43e4ed4b"
consensus_secret_key = "df9652ecd6d5fe9539671c92a7b53b7925b89bd3fbf3ba82b81424c837d0fa4bcbc9ffef062abe970087273f14bfdadbc5d5c5b51cb2fb8a386d960d43e4ed4b"
external_address = "127.0.0.1:5400"
listen_address = "0.0.0.0:5400"
peers = ["127.0.0.1:5400"]
service_public_key = "271b105d5df23b0a1a9f005dd796d4624169fc0e19dd4c24385eef25bf33be5e"
service_secret_key = "7b24495d88ec1f72a83f7afb4e1aa60cf7844320f2e97c4a94c118aa23c66310271b105d5df23b0a1a9f005dd796d4624169fc0e19dd4c24385eef25bf33be5e"

[api]
enable_blockchain_explorer = true
state_update_timeout = 10000

[database]
create_if_missing = true
[[genesis.validator_keys]]
consensus_key = "cbc9ffef062abe970087273f14bfdadbc5d5c5b51cb2fb8a386d960d43e4ed4b"
service_key = "271b105d5df23b0a1a9f005dd796d4624169fc0e19dd4c24385eef25bf33be5e"

[genesis.consensus]
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[mempool]
tx_pool_capacity = 100000

[mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[services_configs.ejb.jvm_config]
class_path = "/Users/katerynanegriienko/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/katerynanegriienko/.m2/repository/org/apache/logging/log4j/log4j-api/2.11.0/log4j-api-2.11.0.jar:/Users/katerynanegriienko/.m2/repository/com/github/jnr/jffi/1.2.9/jffi-1.2.9-native.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-codec-dns/4.1.19.Final/netty-codec-dns-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.5/jackson-core-2.9.5.jar:/Users/katerynanegriienko/.m2/repository/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-codec/4.1.19.Final/netty-codec-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-codec-http2/4.1.19.Final/netty-codec-http2-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/io/vertx/vertx-web/3.5.2/vertx-web-3.5.2.jar:/Users/katerynanegriienko/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/katerynanegriienko/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/katerynanegriienko/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/Users/katerynanegriienko/.m2/repository/io/vertx/vertx-auth-common/3.5.2/vertx-auth-common-3.5.2.jar:/Users/katerynanegriienko/.m2/repository/com/github/jnr/jnr-ffi/2.0.5/jnr-ffi-2.0.5.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-handler/4.1.19.Final/netty-handler-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-resolver-dns/4.1.19.Final/netty-resolver-dns-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/io/vertx/vertx-core/3.5.2/vertx-core-3.5.2.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-resolver/4.1.19.Final/netty-resolver-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/org/abstractj/kalium/kalium/0.8.0/kalium-0.8.0.jar:/Users/katerynanegriienko/.m2/repository/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar:/Users/katerynanegriienko/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-handler-proxy/4.1.19.Final/netty-handler-proxy-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/Users/katerynanegriienko/.m2/repository/io/vertx/vertx-bridge-common/3.5.2/vertx-bridge-common-3.5.2.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-transport/4.1.19.Final/netty-transport-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-codec-http/4.1.19.Final/netty-codec-http-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-buffer/4.1.19.Final/netty-buffer-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-codec-socks/4.1.19.Final/netty-codec-socks-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar:/Users/katerynanegriienko/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/Users/katerynanegriienko/.m2/repository/org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0.jar:/Users/katerynanegriienko/.m2/repository/io/netty/netty-common/4.1.19.Final/netty-common-4.1.19.Final.jar:/Users/katerynanegriienko/.m2/repository/com/google/inject/guice/4.2.0/guice-4.2.0.jar:/Users/katerynanegriienko/.m2/repository/com/github/jnr/jffi/1.2.9/jffi-1.2.9.jar:/Users/katerynanegriienko/Documents/exonum-java-binding/exonum-java-proofs/target/exonum-java-proofs-0.1.0.jar:/Users/katerynanegriienko/.m2/repository/org/apache/logging/log4j/log4j-core/2.11.0/log4j-core-2.11.0.jar:/Users/katerynanegriienko/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar:/Users/katerynanegriienko/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar:/Users/katerynanegriienko/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.5/jackson-databind-2.9.5.jar:/Users/katerynanegriienko/.m2/repository/com/google/auto/value/auto-value-annotations/1.6/auto-value-annotations-1.6.jar:/Users/katerynanegriienko/.m2/repository/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar:/Users/katerynanegriienko/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/Users/katerynanegriienko/Documents/exonum-java-binding/exonum-java-binding-core/target/classes:/Users/katerynanegriienko/Documents/exonum-java-binding/exonum-java-binding-cryptocurrency-demo/target/classes"
debug = false
lib_path = "/Users/katerynanegriienko/Documents/exonum-java-binding/exonum-java-binding-core/rust/target/debug"
log_config_path = "/Users/katerynanegriienko/Documents/exonum-java-binding/exonum-java-binding-core/rust/ejb-app/log4j2.xml"

[services_configs.ejb.service_config]
module_name = "com.exonum.binding.cryptocurrency.ServiceModule"
port = 6000

[whitelist]
whitelist_enabled = false
whitelisted_peers = []
